export const DASHBOARD = {
  loading: 'Загрузка...',

  timeAgo: {
    justNow:    'только что',
    minutesAgo: 'мин назад',
    hoursAgo:   'ч назад',
    daysAgo:    'дн назад',
  },

  nav: {
    logout:       'Выйти',
    guide:        'Гайд',
    profile:      'Профиль',
    balance:      'Баланс',
    hunts:        'Охоты',
    referrals:    'Рефералы',
    devices:      'Устройства',
    transactions: 'Транзакции',
    feedback:     'Идеи',
    roy:          'РОЙ',
    chests:       'Сундуки',
    ancients:     'Древний',
  },

  devices: {
    title:       'Устройства',
    linked:      'Привязанное устройство',
    unlink:      'Отвязать устройство (сброс HWID)',
    nextReset:   'Следующий сброс доступен:',
    linkTitle:   'Привяжи устройство',
    linkSteps:   [
      'Открой Total Hunter на своём компьютере',
      'Перейди на вкладку «Профиль»',
      'Нажми «Создать код привязки»',
      'Введи 6-значный код ниже',
    ],
    codeError:   'Код должен быть 6 цифр',
    linkBtn:     'Привязать',
    placeholder: '000000',
  },

  chests: {
    title: 'Сундуки',
    rawCol: 'Сырой OCR',
    catalogCol: 'Официальный сундук',
    customNameCol: 'Своё название',
    pointsCol: 'Очки',
    inPatternCol: 'В пресете',
    totalEverCol: 'Итого',
    grandTotalLabel: 'Итого всех сундуков:',
    loadPresetBtn: 'Загрузить пресет',
    presetLoaded: 'Пресет применён, не забудь сохранить',
    chestsTab: 'Сундуки',
    playersTab: 'Игроки',
    historyTab: 'История',
    loadHistoryBtn: 'Загрузить историю',
    historyEmpty: 'Архив пока пуст.',
    playerRawCol: 'Сырое имя (OCR)',
    playerCanonicalCol: 'Правильное имя',
    addPlayerRow: 'Добавить игрока вручную',
    savePlayerAliases: 'Сохранить имена',
    seasonTitle: 'Настройки сезона',
    timezoneLabel: 'Часовой пояс',
    periodStartLabel: 'Начало периода',
    periodEndLabel: 'Конец периода',
    targetPointsLabel: 'Цель (очки)',
    targetChestsLabel: 'Цель (сундуки)',
    saveSeason: 'Запустить сезон',
    closeSeasonBtn: 'Закрыть сезон досрочно',
    closeSeasonConfirmText: 'Вы уверены? Текущий сезон будет закрыт и отправлен в историю. Действие необратимо.',
    closeSeasonYes: 'Да, закрыть',
    closeSeasonNo: 'Отмена',
    quotaCol: 'Считать в квоту',
    addRow: 'Добавить сундук вручную',
    save: 'Сохранить',
    saved: 'Сохранено',
    publicLink: 'Публичная страница клана',
    generateToken: 'Сгенерировать код передачи',
    claimPlaceholder: 'Код передачи',
    claimBtn: 'Принять управление',
    noCollectors: 'У вас пока нет ни одного клана. Бот создаёт коллектор автоматически при первой отправке сундуков, или попроси код передачи у того, кто уже его настроил.',
    noCatalog: '— выбрать —',
    language: 'Язык клана',
    deleteCollectorBtn: 'Удалить коллектор',
    deleteCollectorConfirm: 'НАВСЕГДА удалить клан и все его сундуки?',
    deleteCollectorYes: 'Да, удалить',
  },

  ancients: {
    title: 'Древний',
    publicLink: 'Публичная страница клана',
    player: 'Игрок', place: 'Место', points: 'Очки', troopLevel: 'Состав',
    rank: 'Звание', quota: 'Квота',
    noTroopLevel: 'не указан',
    thresholdsTitle: 'Пороги недобора квоты (%)',
    thresholdLight: 'Лёгкий', thresholdMedium: 'Средний', thresholdCritical: 'Критический',
    calcTitle: 'Калькулятор нормы',
    summonsLabel: 'Количество вызовов',
    startLevelLabel: 'Уровень первого Древнего',
    levelsPreviewLabel: 'Уровни вызовов (по нарастающей)',
    powerUnit: 'млн',
    presetLabel: 'Прессет клана',
    amplificationLabel: 'Коэффициент усиления',
    strategyLabel: 'Стратегия',
    strategyA: 'А — по рангу', strategyB: 'Б — по уровню войск',
    strategyAName: 'По рангу', strategyBName: 'По уровню войск',
    officerCount: 'Офицеры', veteranCount: 'Ветераны',
    calculateButton: 'Рассчитать',
    totalQuota: 'Общая норма (млн)',
    officerQuota: 'Норма на офицера', veteranQuota: 'Норма на ветерана',
    excludedNote: 'Без указанного уровня войск (не учтены)',
    historyTitle: 'История расчётов',
    historyLevels: 'Уровни',
    historyTotal: 'Норма',
    noHistory: 'Расчётов пока не было',
    noRoster: 'Ростер пуст — запустите tournament_reader.py на машине лидера.',
    rosterTitle: 'Ростер клана',
    inviteBtn: 'Пригласить сокланера',
    inviteCopied: 'Ссылка скопирована!',
    editorBadge: 'Редактор',
    joinSuccess: 'Доступ получен! Страница обновляется...',
    joinError: 'Ссылка недействительна или истекла',
    hideBtn: 'Скрыть',
    hideConfirm: 'Скрыть из списка? Данные не удаляются, вернуть можно из «Скрытые».',
    hideYes: 'Да, скрыть',
    hiddenSectionTitle: 'Скрытые',
    showBtn: 'Показать',
    manualAddTitle: 'Добавить участника вручную',
    manualNamePlaceholder: 'Имя игрока',
    manualRankLabel: 'Звание',
    manualAddButton: 'Добавить',
    manualSimilarNameWarning: name => `Похоже на «${name}» — использовать это имя?`,
    manualUseSuggested: 'Да, это он',
    manualAddAnyway: 'Нет, добавить как есть',
    manualDuplicateError: 'Такой игрок уже в ростере',
    deleteRosterBtn: 'Удалить',
    deleteRosterYes: 'Да, удалить',
    populateFromChestsBtn: 'Заполнить из Сундуков',
    populateFromChestsConfirm: 'Ростер станет точной копией базы Сундуков — лишние записи (в т.ч. добавленные вручную, если их нет в Сундуках) будут удалены. Продолжить?',
    populateFromChestsYes: 'Да, синхронизировать',
    populateFromChestsResult: (synced, removed) => `Синхронизировано: ${synced}, удалено лишних: ${removed}`,
    tabClans: 'Мои кланы',
    tabHowItWorks: 'Как это работает',
    howItWorksIntro: '«Древний» помогает клану планировать урон по ежедневному событию «Древний»: считает, сколько урона должен нанести каждый игрок, и показывает, кто не дотягивает до нормы.',
    howItWorksSections: [
      {
        title: 'Как игроки попадают в список',
        body: 'Два способа, можно использовать оба сразу. Автоматически — командир открывает в игре статистику турнира «Древний» и нажимает «Старт» на вкладке ДРЕВНИЙ в боте: бот сам считывает таблицу (имя, место, очки) и загружает на сайт. Вручную — в кабинете можно добавить игрока по имени, указать звание и состав войск: удобно для тех, кого бот ещё не увидел в турнирной таблице.',
      },
      {
        title: 'Публичная страница клана',
        body: 'У каждого клана есть отдельная страница-ссылка — без входа в аккаунт, — где игроки сами вписывают своё звание и состав войск, не дожидаясь лидера. Ссылку «🔗 Публичная страница клана» можно скопировать над карточкой клана и скинуть в клан-чат.',
      },
      {
        title: 'Как считается норма',
        body: 'Два способа расчёта. По званию — норма делится между Офицерами и Ветеранами (Офицер получает вдвое больше нормы). По составу войск — норма делится пропорционально силе войск каждого игрока: чем выше тир Земли/Осады/Конницы, тем больше норма.',
      },
      {
        title: 'Если клан уже ведёт Сундуки',
        body: 'Кнопка «Заполнить из Сундуков» подтягивает список игроков клана из Сундуков одним нажатием — не нужно вбивать имена вручную. После нажатия список игроков в Древнем станет точной копией списка в Сундуках (это разовая синхронизация, а не постоянная связь).',
      },
      {
        title: 'Если клан НЕ ведёт Сундуки',
        body: 'Всё работает точно так же: просто добавляйте игроков вручную или дождитесь, пока их подхватит бот из турнирной таблицы. Сундуки для «Древнего» не обязательны.',
      },
      {
        title: 'Совместное редактирование',
        body: 'Лидер может выдать доступ соклановцу — кнопка «Пригласить сокланера» создаёт ссылку, действующую 24 часа. Редактор сможет заполнять состав войск, звания и имена игроков, но не сможет менять расчёт нормы, пороги или скрывать клан — это остаётся только у лидера.',
      },
    ],
  },


  feedback: {
    title:       'Обратная связь',
    sub:         'Есть идея или предложение? Мы читаем каждое сообщение.',
    placeholder: 'Твоя идея или предложение...',
    sending:     'Отправка...',
    send:        'Отправить идею',
  },

  login: {
    title:      'Войти в кабинет',
    sub:        'Используй Google-аккаунт для входа. Первый вход — автоматически создаёт аккаунт.',
    features:   ['Авто-охота на Биржи', 'Поиск Склепов 24/7', 'Реферальная система'],
    signingIn:  'Входим...',
    loginError: 'Ошибка входа: ',
    googleError:  'Ошибка Google авторизации',
    signInGoogle: 'Войти через Google',
    legal:      'Продолжая, ты соглашаешься с',
    legalLink:  'условиями использования',
    guide:      'Гайд',
    home:       '← На главную',
  },

  profile: {
    title: 'Профиль',
    credits:        'Кредиты',
    refCredits:     'Рефералы',
    refCode:        'Реф. код',
    status:         'Статус',
    memberSince:    'С нами с',
    trialUsed:      'Триал использован',
    trialAvailable: '✓ Триал доступен',
    topUp:          'Пополнить кредиты →',
    download:       'Скачать программу',
  },

  recentHunts: {
    title:      'Последние находки',
    empty:      'Ещё нет охот. Запусти Total Hunter! ⚔',
    found:      '— найден',
    looted:     '+ЛУТНУТО',
    allHistory: 'Вся история →',
  },

  huntTypes: {
    exchange: 'Биржа',
    crypt:    'Склеп',
  },

  statTiles: {
    exchangesToday: 'Бирж сегодня',
    cryptsToday:    'Склепов сегодня',
    huntersOnline:  'Охотников онлайн',
  },

  balance: {
    title:         'Баланс',
    diamonds:      'Алмазы',
    refBalance:    'Реферальный баланс',
    sectionBadge:  '⬡ Выбери свой арсенал',
    sectionTitle:  'Пополнение алмазов',
    sectionSub:    'Оплата через NOWPayments (крипто) · Зачисление мгновенно',
    secureNote:    '🔒 Безопасная оплата · NOWPayments · Алмазы не сгорают',
    featuredBadge: '⭐ Выбор охотника',
    bonusDiamonds: '🎁 бонус алмазов',
    baseDiamonds:  'базовых ◆',
    forHunt:       'алмазов на охоту',
    buying:        'Переход...',
    buyBtn:        'Купить —',
    errorPayment:  'Ошибка оплаты',
  },

  hunts: {
    title:         'История охот',
    statToday:     'Сегодня',
    stat7days:     'За 7 дней',
    statTotal:     'Всего охот',
    colType:       'Тип',
    colTime:       'Время',
    empty:         'Охот пока нет. Запусти Total Hunter! ⚔',
    lastRecords:   'последние',
    lastRecordsSuffix: 'записей',
    exchangeLabel: 'Биржи',
    cryptLabel:    'Склепы',
  },

  referrals: {
    title:       'Реферальная программа',
    sub:         'Приглашай охотников — получай % от каждой их покупки',
    linkLabel:   '⬡ Твоя реферальная ссылка',
    copy:        'Копировать',
    copied:      '✓ Скопировано!',
    codeLabel:   'Код:',
    balanceLabel:'Реферальный баланс',
    transferring:'Перевод...',
    transfer:    'Перевести на баланс →',
    howTitle:    'Как работают начисления',
    levels: [
      { level: 'L1', pct: '10%', desc: 'Прямые рефералы (твои приглашённые)',   color: 'var(--accent)'       },
      { level: 'L2', pct: '5%',  desc: 'Рефералы твоих рефералов',              color: '#B060FF'             },
      { level: 'L3', pct: '1%',  desc: 'Третий уровень цепочки',                color: 'var(--credits-gold)' },
    ],
    inviterTitle:  'Код пригласителя',
    inviterSub:    'Если тебя пригласил друг — введи его код и получи +50 ◆ на реф. баланс.',
    inviterBtn:    'Активировать',
    inviterActive: 'Реферальный код активирован',
    perPurchase:   'от суммы каждой покупки',
    note:          'Начисления идут с каждой покупки кредитов по твоей реферальной цепочке. Заблокированные пользователи пропускаются, цепочка продолжается дальше.',
    networkTitle:  'Моя сеть',
    networkPeople: 'чел.',
    treeTitle:     'Реферальная сеть',
    treeEmpty:     'У вас пока нет рефералов',
    treeSince:     'с',
  },

  transactions: {
    title:    'Транзакции',
    colOp:    'Операция',
    colAmount:'Сумма',
    colDate:  'Дата',
    empty:    'Транзакций пока нет',
    types: {
      purchase:               'Покупка кредитов',
      credit_use:             'Охота',
      trial:                  'Триал-бонус',
      ref_welcome:            'Реф. приветствие',
      ref_earning:            'Реф. начисление',
      ref_transfer:           'Рефералы → баланс',
      hwid_duplicate_blocked: 'HWID дубликат',
      manual_adjust:          'Корректировка',
    },
  },
}
