export const DASHBOARD = {
  loading: 'Loading...',

  timeAgo: {
    justNow:     'just now',
    minutesAgo: 'min ago',
    hoursAgo:   'h ago',
    daysAgo:    'd ago',
  },

  nav: {
    logout:       'Logout',
    guide:        'Guide',
    profile:      'Profile',
    balance:      'Balance',
    hunts:        'Hunts',
    referrals:    'Referrals',
    devices:      'Devices',
    transactions: 'Transactions',
    feedback:     'Feedback',
    roy:          'SWARM',
    chests:       'Chests',
    ancients:     'Ancient',
  },

  devices: {
    title:       'Devices',
    linked:      'Linked device',
    unlink:      'Unlink device (reset HWID)',
    nextReset:   'Next reset available:',
    linkTitle:   'Link your device',
    linkSteps:   [
      'Open the bot on your computer',
      'Go to the Profile tab',
      'Click Generate link code',
      'Enter the 6-digit code below',
    ],
    codeError:   'Code must be 6 digits',
    linkBtn:     'Link',
    placeholder: '000000',
  },

  chests: {
    title: 'Chests',
    rawCol: 'Raw OCR',
    catalogCol: 'Official Chest',
    customNameCol: 'Custom Name',
    pointsCol: 'Points',
    inPatternCol: 'In Preset',
    totalEverCol: 'Total',
    grandTotalLabel: 'Total chests of all time:',
    loadPresetBtn: 'Load Preset',
    presetLoaded: 'Preset applied — remember to save',
    chestsTab: 'Chests',
    playersTab: 'Players',
    historyTab: 'History',
    loadHistoryBtn: 'Load history',
    historyEmpty: 'No archived seasons yet.',
    playerRawCol: 'Raw Name (OCR)',
    playerCanonicalCol: 'Correct Name',
    addPlayerRow: 'Add player manually',
    savePlayerAliases: 'Save names',
    seasonTitle: 'Season Settings',
    timezoneLabel: 'Timezone',
    periodStartLabel: 'Period Start',
    periodEndLabel: 'Period End',
    targetPointsLabel: 'Target (Points)',
    targetChestsLabel: 'Target (Chests)',
    saveSeason: 'Start Season',
    closeSeasonBtn: 'Close Season Early',
    closeSeasonConfirmText: 'Are you sure? The current season will be archived. This cannot be undone.',
    closeSeasonYes: 'Yes, close it',
    closeSeasonNo: 'Cancel',
    quotaCol: 'Counts Toward Quota',
    addRow: 'Add chest manually',
    save: 'Save',
    saved: 'Saved',
    publicLink: 'Clan public page',
    generateToken: 'Generate transfer code',
    claimPlaceholder: 'Transfer code',
    claimBtn: 'Claim management',
    noCollectors: "You don't have a clan yet. The bot creates a collector automatically on your first chest submission, or ask for a transfer code from whoever already set one up.",
    noCatalog: '— select —',
    language: 'Clan language',
    deleteCollectorBtn: 'Delete collector',
    deleteCollectorConfirm: 'Permanently delete this clan and ALL its chests?',
    deleteCollectorYes: 'Yes, delete',
  },

  ancients: {
    title: 'Ancient',
    createClanBtn: '➕ Create clan',
    createClanTitle: 'Create clan',
    createClanKingdomLabel: 'Kingdom (number)',
    createClanClanLabel: 'Clan name',
    createClanSubmit: 'Create',
    createClanCancel: 'Cancel',
    createClanError: 'Failed to create clan',
    emptyStateTitle: "You don't manage any clans yet",
    emptyStateBody: 'Create a clan manually, or install the bot — it will pick up the clan automatically on the first report.',
    publicLink: 'Clan public page',
    player: 'Player', place: 'Place', points: 'Points', troopLevel: 'Composition',
    rank: 'Rank', quota: 'Quota',
    noTroopLevel: 'not set',
    thresholdsTitle: 'Quota shortfall thresholds (%)',
    thresholdLight: 'Light', thresholdMedium: 'Medium', thresholdCritical: 'Critical',
    calcTitle: 'Quota calculator',
    summonsLabel: 'Number of summons',
    startLevelLabel: 'First Ancient level',
    levelsPreviewLabel: 'Summon levels (ascending)',
    powerUnit: 'M',
    powerUnitBillion: 'B',
    presetLabel: 'Clan preset',
    amplificationLabel: 'Amplification coefficient',
    strategyLabel: 'Strategy',
    strategyA: 'A — by rank', strategyB: 'B — by troop level',
    strategyAName: 'By rank', strategyBName: 'By troop level',
    officerCount: 'Officers', veteranCount: 'Veterans',
    calculateButton: 'Calculate',
    totalQuota: 'Total quota',
    officerQuota: 'Officer quota', veteranQuota: 'Veteran quota',
    excludedNote: 'Without a troop level set (excluded)',
    historyTitle: 'Calculation history',
    historyLevels: 'Levels',
    historyTotal: 'Quota',
    noHistory: 'No calculations yet',
    noRoster: 'Roster is empty — run tournament_reader.py on the leader\'s machine.',
    rosterTitle: 'Clan roster',
    inviteBtn: 'Invite clanmate',
    inviteCopied: 'Link copied!',
    editorBadge: 'Editor',
    joinSuccess: 'Access granted! Reloading...',
    joinError: 'Invite link is invalid or expired',
    hideBtn: 'Hide',
    hideConfirm: 'Hide from the list? Data is not deleted, restore it from "Hidden".',
    hideYes: 'Yes, hide',
    hiddenSectionTitle: 'Hidden',
    showBtn: 'Show',
    manualAddTitle: 'Add participant manually',
    manualNamePlaceholder: 'Player name',
    manualRankLabel: 'Rank',
    manualAddButton: 'Add',
    manualSimilarNameWarning: name => `Looks like "${name}" — use this name?`,
    manualUseSuggested: 'Yes, that\'s them',
    manualAddAnyway: 'No, add as-is',
    manualDuplicateError: 'This player is already in the roster',
    deleteRosterBtn: 'Delete',
    deleteRosterYes: 'Yes, delete',
    populateFromChestsBtn: 'Populate from Chests',
    populateFromChestsConfirm: 'The roster will become an exact mirror of the Chests base — extra rows (including manually added ones not present in Chests) will be deleted. Continue?',
    populateFromChestsYes: 'Yes, sync',
    populateFromChestsResult: (synced, removed) => `Synced: ${synced}, removed: ${removed}`,
    tabClans: 'My clans',
    tabHowItWorks: 'How it works',
    howItWorksIntro: '"Ancient" helps a clan plan damage for the daily "Ancient" event: it calculates how much damage each player should deal, and shows who is falling short of quota.',
    howItWorksSections: [
      {
        title: 'How players get on the list',
        body: 'Two ways, and you can use both at once. Automatically — the leader opens the in-game "Ancient" tournament statistics and presses "Start" on the ANCIENT tab in the bot: the bot reads the table (name, place, points) itself and uploads it to the site. Manually — in the dashboard you can add a player by name and set their rank and troop composition — handy for anyone the bot hasn\'t seen in the tournament table yet.',
      },
      {
        title: 'Clan public page',
        body: 'Every clan has its own shareable page — no login required — where players enter their own rank and troop composition instead of waiting on the leader. Copy the "🔗 Clan public page" link above the clan card and drop it in clan chat.',
      },
      {
        title: 'How the quota is calculated',
        body: 'Two calculation methods. By rank — the quota is split between Officers and Veterans (an Officer gets twice a Veteran\'s quota). By troop level — the quota is split in proportion to each player\'s troop strength: the higher the Ground/Siege/Mounted tier, the larger the quota.',
      },
      {
        title: 'If the clan already tracks Chests',
        body: 'The "Populate from Chests" button pulls the clan\'s player list from Chests in one click — no need to type names by hand. After clicking, the Ancient roster becomes an exact mirror of the Chests list (this is a one-time sync, not an ongoing link).',
      },
      {
        title: 'If the clan does NOT track Chests',
        body: 'Everything works exactly the same way: just add players manually, or wait for the bot to pick them up from the tournament table. Chests is not required for Ancient.',
      },
      {
        title: 'Sharing access with a clanmate',
        body: 'The leader can grant a clanmate access — the "Invite clanmate" button creates a link valid for 24 hours. An editor can fill in troop levels, ranks, and player names, but cannot change the quota calculation, thresholds, or hide the clan — that stays with the leader only.',
      },
    ],
  },

  feedback: {
    title:       'Feedback',
    sub:         'Got an idea or suggestion? We read every message.',
    placeholder: 'Your idea or suggestion...',
    sending:     'Sending...',
    send:        'Send Idea',
  },

  login: {
    title:      'Sign In',
    sub:        'Use your Google account to sign in. First login automatically creates an account.',
    features:   ['Auto-hunt for Exchanges', '24/7 Crypt Search', 'Referral System'],
    signingIn:  'Signing in...',
    loginError: 'Login error: ',
    googleError:  'Google authorization error',
    signInGoogle: 'Sign in with Google',
    legal:      'By continuing, you agree to the',
    legalLink:  'terms of service',
    guide:      'Guide',
    home:       '← Back to home',
  },

  profile: {
    title: 'Profile',
    credits:        'Credits',
    refCredits:     'Referrals',
    refCode:        'Ref. code',
    status:         'Status',
    memberSince:    'Member since',
    trialUsed:      'Trial used',
    trialAvailable: '✓ Trial available',
    topUp:          'Top up credits →',
    download:       'Download Bot',
  },

  recentHunts: {
    title:      'Recent Finds',
    empty:      'No hunts yet. Start the bot! ⚔',
    found:      '— found',
    looted:     '+LOOTED',
    allHistory: 'Full history →',
  },

  huntTypes: {
    exchange: 'Exchange',
    crypt:    'Crypt',
  },

  statTiles: {
    exchangesToday: 'Exchanges today',
    cryptsToday:    'Crypts today',
    huntersOnline:  'Hunters online',
  },

  balance: {
    title:          'Balance',
    diamonds:       'Diamonds',
    refBalance:     'Referral balance',
    sectionBadge:   '⬡ Choose your arsenal',
    sectionTitle:   'Top up diamonds',
    sectionSub:     'Payment via NOWPayments (crypto) · Instant delivery',
    secureNote:     '🔒 Secure payment · NOWPayments · Diamonds do not expire',
    featuredBadge: '⭐ Hunter\'s Choice',
    bonusDiamonds: '🎁 bonus diamonds',
    baseDiamonds:  'base ◆',
    forHunt:       'diamonds per hunt',
    buying:         'Redirecting...',
    buyBtn:         'Buy —',
    errorPayment:   'Payment error',
  },

  hunts: {
    title:         'Hunt History',
    statToday:     'Today',
    stat7days:     'Last 7 days',
    statTotal:     'Total hunts',
    colType:       'Type',
    colTime:       'Time',
    empty:         'No hunts yet. Start the bot! ⚔',
    lastRecords:   'last',
    lastRecordsSuffix: 'records',
    exchangeLabel: 'Exchanges',
    cryptLabel:    'Crypts',
  },

  referrals: {
    title:       'Referral Program',
    sub:         'Invite hunters — earn % from their every purchase',
    linkLabel:   '⬡ Your referral link',
    copy:        'Copy',
    copied:      '✓ Copied!',
    codeLabel:   'Code:',
    balanceLabel:'Referral balance',
    transferring:'Transferring...',
    transfer:    'Transfer to balance →',
    howTitle:    'How earnings work',
    levels: [
      { level: 'L1', pct: '10%', desc: 'Direct referrals (invited by you)',   color: 'var(--accent)'      },
      { level: 'L2', pct: '5%',  desc: 'Referrals of your referrals',              color: '#B060FF'             },
      { level: 'L3', pct: '1%',  desc: 'Third chain level',                 color: 'var(--credits-gold)' },
    ],
    inviterTitle:  'Inviter Code',
    inviterSub:    'If a friend invited you — enter their code and get +50 ◆ to your referral balance.',
    inviterBtn:    'Activate',
    inviterActive: 'Referral code activated',
    perPurchase:   'of every purchase amount',
    note:          'Earnings are generated from every credit purchase in your referral chain. Blocked users are skipped, and the chain continues.',
    networkTitle:  'My Network',
    networkPeople: 'people',
    treeTitle:     'Referral Network',
    treeEmpty:     'No referrals yet',
    treeSince:     'since',
  },

  transactions: {
    title:    'Transactions',
    colOp:    'Operation',
    colAmount:'Amount',
    colDate:  'Date',
    empty:    'No transactions yet',
    types: {
      purchase:               'Credit purchase',
      credit_use:             'Hunting',
      trial:                  'Trial bonus',
      ref_welcome:            'Ref. welcome',
      ref_earning:            'Ref. accrual',
      ref_transfer:           'Referrals → balance',
      hwid_duplicate_blocked: 'HWID duplicate',
      manual_adjust:          'Adjustment',
    },
  },
}