export const DASHBOARD = {
  loading: 'Загрузка...',

  timeAgo: {
    justNow:    'только что',
    minutesAgo: 'мин назад',
    hoursAgo:   'ч назад',
    daysAgo:    'дн назад',
  },

  nav: {
    logout:       'Выйти',
    guide:        'Гайд',
    profile:      'Профиль',
    balance:      'Баланс',
    hunts:        'Охоты',
    referrals:    'Рефералы',
    devices:      'Устройства',
    transactions: 'Транзакции',
    feedback:     'Идеи',
  },

  devices: {
    title:       'Устройства',
    linked:      'Привязанное устройство',
    unlink:      'Отвязать устройство (сброс HWID)',
    nextReset:   'Следующий сброс доступен:',
    linkTitle:   'Привяжи устройство',
    linkSteps:   [
      'Открой бота на своём компьютере',
      'Перейди на вкладку «Профиль»',
      'Нажми «Создать код привязки»',
      'Введи 6-значный код ниже',
    ],
    codeError:   'Код должен быть 6 цифр',
    linkBtn:     'Привязать',
    placeholder: '000000',
  },

  feedback: {
    title:       'Обратная связь',
    sub:         'Есть идея или предложение? Мы читаем каждое сообщение.',
    placeholder: 'Твоя идея или предложение...',
    sending:     'Отправка...',
    send:        'Отправить идею',
  },

  login: {
    title:      'Войти в кабинет',
    sub:        'Используй Google-аккаунт для входа. Первый вход — автоматически создаёт аккаунт.',
    features:   ['Авто-охота на Биржи', 'Поиск Склепов 24/7', 'Реферальная система'],
    signingIn:  'Входим...',
    loginError: 'Ошибка входа: ',
    googleError:  'Ошибка Google авторизации',
    signInGoogle: 'Войти через Google',
    legal:      'Продолжая, ты соглашаешься с',
    legalLink:  'условиями использования',
    guide:      'Гайд',
    home:       '← На главную',
  },

  profile: {
    title: 'Профиль',
    credits:        'Кредиты',
    refCredits:     'Рефералы',
    refCode:        'Реф. код',
    status:         'Статус',
    memberSince:    'С нами с',
    trialUsed:      'Триал использован',
    trialAvailable: '✓ Триал доступен',
    topUp:          'Пополнить кредиты →',
    download:       'Скачать бота',
  },

  recentHunts: {
    title:      'Последние находки',
    empty:      'Ещё нет охот. Запусти бота! ⚔',
    found:      '— найден',
    looted:     '+ЛУТНУТО',
    allHistory: 'Вся история →',
  },

  huntTypes: {
    exchange: 'Биржа',
    crypt:    'Склеп',
  },

  statTiles: {
    exchangesToday: 'Бирж сегодня',
    cryptsToday:    'Склепов сегодня',
    huntersOnline:  'Охотников онлайн',
  },

  balance: {
    title:         'Баланс',
    diamonds:      'Алмазы',
    refBalance:    'Реферальный баланс',
    sectionBadge:  '⬡ Выбери свой арсенал',
    sectionTitle:  'Пополнение алмазов',
    sectionSub:    'Оплата через NOWPayments (крипто) · Зачисление мгновенно',
    secureNote:    '🔒 Безопасная оплата · NOWPayments · Алмазы не сгорают',
    featuredBadge: '⭐ Выбор охотника',
    bonusDiamonds: '🎁 бонус алмазов',
    baseDiamonds:  'базовых ◆',
    forHunt:       'алмазов на охоту',
    buying:        'Переход...',
    buyBtn:        'Купить —',
    errorPayment:  'Ошибка оплаты',
  },

  hunts: {
    title:         'История охот',
    statToday:     'Сегодня',
    stat7days:     'За 7 дней',
    statTotal:     'Всего охот',
    colType:       'Тип',
    colTime:       'Время',
    empty:         'Охот пока нет. Запусти бота! ⚔',
    lastRecords:   'последние',
    lastRecordsSuffix: 'записей',
    exchangeLabel: 'Биржи',
    cryptLabel:    'Склепы',
  },

  referrals: {
    title:       'Реферальная программа',
    sub:         'Приглашай охотников — получай % от каждой их покупки',
    linkLabel:   '⬡ Твоя реферальная ссылка',
    copy:        'Копировать',
    copied:      '✓ Скопировано!',
    codeLabel:   'Код:',
    balanceLabel:'Реферальный баланс',
    transferring:'Перевод...',
    transfer:    'Перевести на баланс →',
    howTitle:    'Как работают начисления',
    levels: [
      { level: 'L1', pct: '10%', desc: 'Прямые рефералы (твои приглашённые)',   color: 'var(--accent)'       },
      { level: 'L2', pct: '5%',  desc: 'Рефералы твоих рефералов',              color: '#B060FF'             },
      { level: 'L3', pct: '1%',  desc: 'Третий уровень цепочки',                color: 'var(--credits-gold)' },
    ],
    inviterTitle:  'Код пригласителя',
    inviterSub:    'Если тебя пригласил друг — введи его код и получи +50 ◆ на реф. баланс.',
    inviterBtn:    'Активировать',
    inviterActive: 'Реферальный код активирован',
    perPurchase:   'от суммы каждой покупки',
    note:          'Начисления идут с каждой покупки кредитов по твоей реферальной цепочке. Заблокированные пользователи пропускаются, цепочка продолжается дальше.',
    networkTitle:  'Моя сеть',
    networkPeople: 'чел.',
  },

  transactions: {
    title:    'Транзакции',
    colOp:    'Операция',
    colAmount:'Сумма',
    colDate:  'Дата',
    empty:    'Транзакций пока нет',
    types: {
      purchase:               'Покупка кредитов',
      credit_use:             'Охота',
      trial:                  'Триал-бонус',
      ref_welcome:            'Реф. приветствие',
      ref_earning:            'Реф. начисление',
      ref_transfer:           'Рефералы → баланс',
      hwid_duplicate_blocked: 'HWID дубликат',
      manual_adjust:          'Корректировка',
    },
  },
}
